name: 'build'
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.6
    - uses: cachix/install-nix-action@v15
    - run: nix --experimental-features 'nix-command flakes' build -L
    - name: "Copy TI-84 Forth artifacts"
      run: cp result/forth.8xk result/forth.8xp .
    - name: "Upload Flash App"
      uses: actions/upload-artifact@v4.3.3
      with:
        name: forth-flash-app
        path: forth.8xk
    - name: "Upload legacy assembly program"
      uses: actions/upload-artifact@v4.3.3
      with:
        name: forth-legacy-program
        path: forth.8xp
